// Este é o seu banco de dados de situações. 
// Para adicionar novos, basta seguir o padrão.
const dbSituacoes = [
    { cod: "A0", desc: "EXERCICIO REGULAR", detalhe: "Exercicio regular" },
    { cod: "A1", desc: "ATIVO NAO REMUNERADO", detalhe: "Ativo não remunerado" },
    { cod: "A2", desc: "EM PROCESSO DE APOSENTADORIA", detalhe: "Em processo de aposentadoria" },
    { cod: "A3", desc: "ESTATUTARIO EM CARGO COMISSIONADO", detalhe: "Estatutário em cargo comissionado" },
    { cod: "A4", desc: "AGUARDANDO APOSENTADORIA ATIVO", detalhe: "Aguardando aposentadoria ativo" },
    { cod: "A5", desc: "AGUARDANDO APOSENTADORIA AFASTADO", detalhe: "Aguardando aposentadoria afastado" },
    { cod: "A6", desc: "AFASTADO PARA CURSO SEM GANHOS", detalhe: "Afastado para curso sem ganhos" },
    { cod: "A7", desc: "SEGREGADO", detalhe: "Militar segregado" },
    { cod: "A8", desc: "EXERCER CARGO ELETIVO REMUNERADO", detalhe: "Exercendo cargo eletivo remunerado" },
    { cod: "A9", desc: "TELETRABALHO", detalhe: "Teletrabalho" },
    { cod: "AB", desc: "AGREGADO SEM SOLDO", detalhe: "Agregado sem soldo" },
    { cod: "AD", desc: "AGUARDANDO DISPENSA", detalhe: "Aguardando dispensa" },
    { cod: "AE", desc: "AGUARDANDO EXONERAÇÃO", detalhe: "Aguardando exoneração" },
    { cod: "AG", desc: "AGUARDANDO DESIGNACAO", detalhe: "Aguardando designação" },
    { cod: "AI", desc: "PAGAMENTO INDENIZATORIO", detalhe: "Aguardando pagamento indenizatório" },
    { cod: "AP", desc: "APROVEITADO", detalhe: "Aproveitado" },
    { cod: "AR", desc: "AGUARDANDO RESCISAO DE CONTRATO", detalhe: "Aguardando rescisão de contrato" },
    { cod: "B0", desc: "LICENCA PARA MATERNIDADE", detalhe: "Licença maternidade" },
    { cod: "B1", desc: "LICENCA MEDICA", detalhe: "Licença médica" },
    { cod: "B2", desc: "LICENCA PELO INSS", detalhe: "Licença pelo INSS" },
    { cod: "B3", desc: "LICENCA PARA SERVICO MILITAR", detalhe: "Licença para serviço militar" },
    { cod: "B4", desc: "LICENCA POR ACIDENTE DE TRABALHO", detalhe: "Licença por aciente de trabalho" },
    { cod: "B5", desc: "LICENCA PARA INTERESSE PARTICULAR", detalhe: "Licença para interesse particular" },
    { cod: "B6", desc: "LICENCA P/ ACOMP PESSOA DA FAMILIA", detalhe: "Licença para acompanhar pessoa da família" },
    { cod: "B7", desc: "LICENCA PARA ACOMPANHAR CONJUGE", detalhe: "Licença para acompnahar conjuge" },
    { cod: "B8", desc: "LICENCA PARA EXERCER CARGO ELETIVO", detalhe: "Licença para exercer cargo eletivo" },
    { cod: "B9", desc: "LICENCA PARA FAZER CURSO", detalhe: "Licença para fazer curso" },
    { cod: "BA", desc: "LICENCA MEDICA PMM", detalhe: "Licença médica Prefeitura de Manaus" },
    { cod: "BM", desc: "LICENCA EXTENSAO MATERNIDADE", detalhe: "Licença maternidade - extensão" },
    { cod: "BP", desc: "LICENCA PATERNIDADE", detalhe: "Licença paternidade" },
    { cod: "C0", desc: "LICENCA ESPECIAL", detalhe: "Licença especial" },
    { cod: "C1", desc: "LICENCA P/CONCORRER A CARGO ELETIVO", detalhe: "Licença para concorrer a cargo eletivo" },
    { cod: "C2", desc: "AFASTADO P/ ESTUDO OU MISSAO ESPEC.", detalhe: "Afastado para estudo ou missão especial" },
    { cod: "C3", desc: "LICENCA MATERNIDADE PATRONAL", detalhe: "Licença maternidade patronal" },
    { cod: "D0", desc: "DISPONIVEL", detalhe: "Disponível" },
    { cod: "D1", desc: "DESERTOR", detalhe: "Desertor" },
    { cod: "D2", desc: "DISPENSA TEMPORARIO A PEDIDO", detalhe: "Temporário dispensado a pedido do servidor" },
    { cod: "D3", desc: "DISPENSA TEMPORARIO PELO EMPREGADOR", detalhe: "Teporário dispensado pelo empregador" },
    { cod: "D4", desc: "DISPENSA TERMINO BOLSA RESIDENCIA", detalhe: "Termino bolsa residência" },
    { cod: "D5", desc: "DISPENSA DE BOLSISTA A PEDIDO", detalhe: "Bolsista dispensado a peddo do servidor" },
    { cod: "D6", desc: "DISPONIBILIZDO TRIBUNAL JURI", detalhe: "Disponibilizado para tribunal do juri" },
    { cod: "D7", desc: "DISPENSA TEMPORARIO TERMINO CONTRAT", detalhe: "Temporário dispensado por termino de contrato" },
    { cod: "D8", desc: "DEMIT. P/ EMPREGADOR C/ JUSTA CAUSA", detalhe: "Demitido pelo empregador com justa causa" },
    { cod: "E0", desc: "APOSENTADO POR TEMPO DE SERVICO", detalhe: "Aposentado por tempo de serviço" },
    { cod: "E1", desc: "APOSENTADO POR INVALIDEZ", detalhe: "Aposentado por invalidez" },
    { cod: "E2", desc: "APOSENTADORIA COMPULSORIA", detalhe: "Aposentado compulsoriamente" },
    { cod: "E3", desc: "REFORMADO DA POLICIA MILITAR", detalhe: "Reformado da Policia Militar" },
    { cod: "E4", desc: "APOSENTADO P/INVALIDEZ PROPORCIONAL", detalhe: "Aposentado por invalidez proporcional" },
    { cod: "E5", desc: "APOSENTADO TEMPO SERV. PROPORCIONAL", detalhe: "Aposentado por tempo de serviço proporcional" },
    { cod: "E6", desc: "APOSENTADO COMPULSORIA PROPORCIONAL", detalhe: "Aposentado compulsoriamente proporcional" },
    { cod: "E7", desc: "APOSENTADORIA PROPORCIONAL EMENDA36", detalhe: "Aposentado proporcionalmente pela Emenda 36" },
    { cod: "E8", desc: "APOSENTADO P/ IDADE PROPORCIONAL", detalhe: "Aposentado por idade proporcional" },
    { cod: "E9", desc: "APOSENTADORIA CANCELADA", detalhe: "Aposentadoria cancelada" },
    { cod: "EA", desc: "APOSENTADO CONTRIBUICAO MEDIA", detalhe: "Aposentado por contribuição media" },
    { cod: "EB", desc: "APOSENTADO PROFESSOR PARIDADE", detalhe: "Professor aposentado por paridade" },
    { cod: "EC", desc: "EXTINCAO DE CONVENIO", detalhe: "Extinção de convenio" },
    { cod: "ED", desc: "APOSENTADO INVALIDEZ MEDIA", detalhe: "Aposentado por invalidez media" },
    { cod: "EE", desc: "APOSENTADO INVALIDEZ MEDIA PROPORCI", detalhe: "Aposentado por inlidez media proporcional" },
    { cod: "EF", desc: "APOSENTADO RPC - TETO RGPS", detalhe: "Aposentado RPC - Regime de Previdencia Complementar - TETO RGPS" },
    { cod: "EG", desc: "APOSENTADORIA REGIME GERAL", detalhe: "Aposentado RGPS - Regime Geral de Previdência Social" },
    { cod: "EH", desc: "APOSENTADO PROFESSOR MEDIA", detalhe: "Professor aposentado media" },
    { cod: "EI", desc: "APOSENTADO ESPECIAL - RISCO", detalhe: "Aposentado especial por risco" },
    { cod: "EJ", desc: "APOSENTADO COM DEFICIENCIA", detalhe: "Aposentado com deficiencia" },
    { cod: "EK", desc: "APOSENTADO ESPECIAL - POLICIA CIVIL", detalhe: "Aposentado especial da Policia Civil" },
    { cod: "EL", desc: "APOSENTADO ESPECIAL - RISCO RPC", detalhe: "Aposentado especial por risco - RPC - Regime de Previdência Complementar" },
    { cod: "EM", desc: "APOSENTADO ESPECIAL - AGENTE NOCIVO", detalhe: "Aposentado especial por agente nocivo" },
    { cod: "EN", desc: "APOSENTADO COM DEFICIENCIA RPC", detalhe: "Aposentado com deficiencia RPC - Regime de Previdência Complementar" },
    { cod: "EO", desc: "APOSENTADO ESPECIAL - POLICIA CIVIL", detalhe: "Aposentado especial - Policia Civil" },
    { cod: "EP", desc: "APOSENTADO ESPECIAL - AGENTE NOCIVO", detalhe: "Aposentado especial por agente nocivo" },
    { cod: "EQ", desc: "APOSENTADO INVALIDEZ RPC", detalhe: "Aposentado por invelidez - RPC - Regime de Previdência Complementar" },
    { cod: "ES", desc: "APOSENTADO BENEFICIARIO", detalhe: "Aposentado beneficiário" },
    { cod: "F0", desc: "DEMIT. P/ EMPREGADOR C/ JUSTA CAUSA", detalhe: "Demitido pelo empregador com justa causa" },
    { cod: "F1", desc: "EXONERADO PELO EMPREGADOR", detalhe: "Exonerado pelo empregador" },
    { cod: "F2", desc: "DEMITIDO P/ EMPREGADO C/ JUST CAUSA", detalhe: "Demitido pelo empregado com justa causa" },
    { cod: "F3", desc: "EXONERADO A PEDIDO DO SERVIDOR", detalhe: "Exonerado a pedido do servidor" },
    { cod: "F4", desc: "APOSENTADO", detalhe: "Aposentado" },
    { cod: "F5", desc: "FALECIDO", detalhe: "Falecido" },
    { cod: "F6", desc: "DEMITIDO POR OUTROS MOTIVOS", detalhe: "Demitido por outros motivos" },
    { cod: "F7", desc: "APOSENTADORIA CANCELADA POR ACUMULO", detalhe: "Aposentadoria cancelada por acumulo" },
    { cod: "F8", desc: "DEMITIDO POR ACUMULO CARGO PROIBIDO", detalhe: "Demitido por acumulo de cargo proibido" },
    { cod: "F9", desc: "APOSENTADORIA EXCLUIDA PELO TCE", detalhe: "Aposentadoria excluida pelo TCE" },
    { cod: "FA", desc: "AUSENCIA (JUDICIAL)", detalhe: "Ausencia judicial" },
    { cod: "FV", desc: "EXONERACAO - VACANCIA DE CARGO", detalhe: "Exoneração por vacancia de cargo" },
    { cod: "G0", desc: "RELOTADO", detalhe: "Relotado" },
    { cod: "G1", desc: "REDISTRIBUIDO", detalhe: "Redistribuido" },
    { cod: "G2", desc: "MUDANCA DE CNPJ", detalhe: "Mudanã de CNPJ" },
    { cod: "G3", desc: "MUDANCA DE CARGO COMISSIONADO", detalhe: "Mudança de cargo comissionado" },
    { cod: "G4", desc: "AGRUPADO", detalhe: "Agrupado" },
    { cod: "G5", desc: "MUDANCA DE ORGAO", detalhe: "Mudança de órgão" },
    { cod: "G6", desc: "ALTERACAO DE REGIME JURIDICO", detalhe: "Alteração de regime jurídico" },
    { cod: "H0", desc: "RECEBENDO SUBSIDIOS", detalhe: "Recebendo subsídio" },
    { cod: "H1", desc: "RECEBIMENTO DE SUBSIDIOS CESSADO", detalhe: "Recebimento de subsidio cessado" },
    { cod: "H2", desc: "RECEBENDO PENSAO DE HANSENIANO", detalhe: "Recebendo pensão hanseniano" },
    { cod: "H3", desc: "RECEB. DE PENSAO DE HANSEN. CESSADA", detalhe: "Recebimento de pensão hanseniano cessada" },
    { cod: "H4", desc: "RECEBENDO COTA DOS HERDEIROS", detalhe: "Recebendo cota dos herdeiros" },
    { cod: "H5", desc: "RECEB. DE COTA DOS HERDEIR. CESSADA", detalhe: "Recebendo cotas dos herdeiros cessado" },
    { cod: "H6", desc: "RECEBENDO COMO ESTAGIARIO", detalhe: "Recebendo como estagiário" },
    { cod: "H7", desc: "RECEBIMENTO C/ ESTAGIARIO CESSADO", detalhe: "Recebendo como estagiário cessado" },
    { cod: "H8", desc: "RECEBENDO PENSAO ESPECIAL", detalhe: "Recebendo pensão especial" },
    { cod: "H9", desc: "RECEB. DE PENSAO ESPECIAL CESSADA", detalhe: "Recebendo pensão especial cessada" },
    { cod: "I0", desc: "INSTITUIDOR ATIVO SEM PENSIONISTA", detalhe: "Instituidor ativo sem pensionista" },
    { cod: "I1", desc: "INSTITUIDOR RGPS", detalhe: "Instituidor RGPS - Regime Geral de Previdência Social" },
    { cod: "I2", desc: "RESCIS. CULPA RECIPROCA/FORCA MAIOR", detalhe: "Rescisão por culpa reciproca ou força maior" },
    { cod: "I3", desc: "RESCIS. TERMINO CONTRATO A TERMO", detalhe: "Rescisão por término de contrato a termo" },
    { cod: "IC", desc: "INSTITUIDOR CESSADO", detalhe: "Instituidor cessado" },
    { cod: "IP", desc: "INSTITUIDOR ATIVO COM PENSIONISTA", detalhe: "Instituidor ativo com pensionista" },
    { cod: "J1", desc: "COMPL.APOSENT. POR DECISAO JUDICIAL", detalhe: "Complementação de aposentado por decisão judicial" },
    { cod: "K0", desc: "EXCLUIDO", detalhe: "Excluído" },
    { cod: "K1", desc: "EXCLUIDO POR UNIFICACAO", detalhe: "Excluído por unificação" },
    { cod: "K2", desc: "BENEFICIO CESSADO", detalhe: "Benefício cessado" },
    { cod: "K3", desc: "EXCLUIDO PELO TCE", detalhe: "Excluído pelo TCE" },
    { cod: "K4", desc: "EFETIVADOS PELA E.C. NUM 51/2006", detalhe: "Efetivados pela Emenda Constitucional Nº 51/2006" },
    { cod: "L1", desc: "AFAST.TEMP.DOENCA ATE 15 DIAS EST.", detalhe: "Afastamento temporário por doença de até 15 dias - Estatutário" },
    { cod: "L2", desc: "AFAST.TEMP.DOENÇA SUP.15 DIAS EST.", detalhe: "Afastamento temporário por doença superior a 15 dias - Estatutário" },
    { cod: "L3", desc: "NOVO AFAST.TEMP.DOENÇA 60 DIAS EST.", detalhe: "Novo afastamento temporário por doença 60 dias - Estatutário" },
    { cod: "LS", desc: "LEGADO DE SUSPENSOS", detalhe: "Legado de suspensos" },
    { cod: "M0", desc: "MUDANCA DE REGIME ESTATUTARIO", detalhe: "Mudança de regime estatutário" },
    { cod: "M1", desc: "AFAST.TEMP.ACID.TRAB.15 DIAS EST.", detalhe: "Afastamento temporário por acidente de trabalho de até 15 dias - Estatutário" },
    { cod: "M2", desc: "AFAST.TEMP.ACID.TRAB.SUP.15 D.EST.", detalhe: "Afastamento temporário por aciente de tranalho superior a 15 dias - Estatutário" },
    { cod: "M3", desc: "NOVO AFAST.TEMP.ACID.TRAB.60 D.EST.", detalhe: "Novo afastamento temporário por aciente de trabalho 60 dias - Estatutário" },
    { cod: "M4", desc: "AFAST.TEMP.ACID.15D.CEL.COM.TEM.CLT", detalhe: "Afastamento temporário por acidente de trabalho de até 15 dias - Celetista" },
    { cod: "M5", desc: "AFAST.T.AC.TRAB.SUP.15D.CEL.CT-CLT", detalhe: "Afastamento temporário por aciente de tranalho superior a 15 dias - Celetista" },
    { cod: "M6", desc: "NOVO AFAST.TEMP.60D.CEL.COM.TEMPOR.", detalhe: "Novo afastamento temporário por aciente de trabalho 60 dias - Celetista" },
    { cod: "N1", desc: "LICENÇA MATERNIDADE P/ESTATUTARIO", detalhe: "Licença maternidade para estatutário" },
    { cod: "N2", desc: "AFAST.TEMP.EST.ABORTO NAO CRIM.EST.", detalhe: "Afastamento temporário por abordo não criminal - Estatutário" },
    { cod: "O1", desc: "AFAST.TEMP.ACID/TRAB.SUP 15 DIAS", detalhe: "Afastamento temporário por acidente de trabalho superior a 15 dias" },
    { cod: "O2", desc: "NOVO AFAST.TEMP.DEC MESMO ACIDENTE", detalhe: "Novo afastamento temporário decorrente do mesmo acidente" },
    { cod: "O3", desc: "AFAST.TEMP.ACID./TRAB. ATE 15 DIAS", detalhe: "Afastamento temporário por acidente de trabalho de até 15 dias" },
    { cod: "P1", desc: "AFAST.TEMP.MOTI./DOENCA SUP 15 DIAS", detalhe: "Afastamento temporário por motivo de doença superior a 15 dias" },
    { cod: "P2", desc: "NOVO AFAST.TEMP.MESMA DOENCA ATE 60", detalhe: "Novo afastamento temporário decorrente da mesma doença até 60 dias" },
    { cod: "P3", desc: "AFAST.TEMP.POR DOENCA ATE 15 DIAS", detalhe: "Afastamento temporario por doença de até 15 dias" },
    { cod: "P4", desc: "PERDA CARGO SENTENCA TRANSI.JULGADO", detalhe: "Perda de cargo tendo uma sentença transitado em julgado" },
    { cod: "P5", desc: "PENSAO MENOR ATE 21 ANOS", detalhe: "Pensionista menor até 21 anos" },
    { cod: "P6", desc: "PENSAO MENOR ATE 21 ANOS EXT AOS 24", detalhe: "Pensionista menor de até 21 anos extendido até os 24 anos" },
    { cod: "P7", desc: "PENSAO CONJUGE/COMPANHE POR 4 MESES", detalhe: "Pensionista conjuge/companheiro por 4 meses" },
    { cod: "P8", desc: "PENSAO CONJUGE/COMPANHE POR 03 ANOS", detalhe: "Pensionista conjuge/companheiro por 3 anos" },
    { cod: "P9", desc: "PENSAO CONJUGE/COMPANHE POR 06 ANOS", detalhe: "Pensionista conjuge/companheiro por 6 anos" },
    { cod: "PA", desc: "PENSAO ATIVA", detalhe: "Pensionista ativo" },
    { cod: "PE", desc: "PENSAO EXCLUIDA", detalhe: "Pensionista excluido" },
    { cod: "PI", desc: "PENSAO VITALICIA AO MENOR INVALIDO", detalhe: "Pensionista vitalicio a menor invalido" },
    { cod: "PM", desc: "PENSAO MENOR ATE 18 ANOS", detalhe: "Pensionista menor até 18 anos" },
    { cod: "PP", desc: "PENSAO POR PARIDADE", detalhe: "Pensionita por paridade" },
    { cod: "PS", desc: "PENSAO SUSPENSA", detalhe: "Pensão suspensa" },
    { cod: "PV", desc: "PENSAO VITALICIA CONJUGE/COMPANHEIR", detalhe: "Pensionista vitalicio conjuge/companheiro" },
    { cod: "PX", desc: "PENSAO CONJUGE/COMPANHE POR 10 ANOS", detalhe: "Pensionista conjuge/companheiro por 10 anos" },
    { cod: "PY", desc: "PENSAO CONJUGE/COMPANHE POR 15 ANOS", detalhe: "Pensionista conjuge/companheiro por 15 anos" },
    { cod: "PZ", desc: "PENSAO CONJUGE/COMPANHE POR 20 ANOS", detalhe: "Pensionista conjuge/companheiro por 20 anos" },
    { cod: "Q2", desc: "PROR.AFAST./TEMP.LIC./MATERNIDADE", detalhe: "afastamento temporário de licença maternidade prorrogado" },
    { cod: "Q3", desc: "AFAST.TEMP.ABORTO NAO CRIMINOSO", detalhe: "Afastamento temporário por aborto não criminoso" },
    { cod: "Q4", desc: "LIC/MATER.ADOCAO JUD CRIANCA(1)ANO", detalhe: "Licença maternidade por adoção judicial de criança de 1 ano" },
    { cod: "Q5", desc: "LIC/MATER.ADOCAO JUD DE 1-4 ANOS", detalhe: "Licença materninade por adoção judicial de criança de 1 a 4 anos" },
    { cod: "Q6", desc: "LIC/MATER.ADOCAO JUD DE 4-8 ANOS", detalhe: "Licença materninade por adoção judicial de criança de 4 a 8 anos" },
    { cod: "Q7", desc: "LICENCA MATER.POR ADOÇAO JUD.CELET.", detalhe: "Licença maternidade por adoção judicial - Celetista" },
    { cod: "R1", desc: "AGUARDANDO RESERVA", detalhe: "Aguardando reserva" },
    { cod: "R9", desc: "REVERSAO APOSENTADORIA", detalhe: "Reversão de aposentadoria" },
    { cod: "RE", desc: "REMANEJADOS", detalhe: "Remanejados" },
    { cod: "RS", desc: "PAGAMENTO RESCISAO SERVIDOR", detalhe: "Pagamento de rescisão de servidor" },
    { cod: "RV", desc: "RECEBENDO VERBA RESIDUAL", detalhe: "Recebimento de verba residual" },
    { cod: "S0", desc: "SUSTADO DE FOLHA DE PAGAMENTO", detalhe: "Sustado de folha de pagamento" },
    { cod: "S1", desc: "SUSTADO de FOLHA P/ACUMULO DE CARGO", detalhe: "Sustado de folha de pagamento por acumulo de cargo" },
    { cod: "S2", desc: "SUSTADO, APOSENT.NAO SE RECADASTROU", detalhe: "Sustado por aposentado não se recadastrou" },
    { cod: "S3", desc: "SUSTADO, DISPOSICAO/LICENCA VENCIDA", detalhe: "Sustado por disposição/licença vencida" },
    { cod: "S4", desc: "SUSTADO POR FALTA DE RECENSEAMENTO", detalhe: "Sustado por falta de recenseamento" },
    { cod: "S5", desc: "EXCLUIDO POR MAIORIDADE", detalhe: "Excluido por maioridade" },
    { cod: "S6", desc: "SUSPENSAO DE CONTRATO - C.L.T.", detalhe: "Suspensão de contrato - Celetista" },
    { cod: "S7", desc: "SUSPENSAO POR AGENDAMENTO INSS", detalhe: "Suspensão por agendamento INSS" },
    { cod: "S8", desc: "SUSPENSAO-SEM REATIVACAO EM 90 DIAS", detalhe: "Suspensão sem reativação em 90 dias" },
    { cod: "SC", desc: "SUSTADO PARA CURSO COMO ALUNO", detalhe: "Sustado para curso como aluno" },
    { cod: "SD", desc: "SUSPENSO POR DECISAO DO COLEGIADO", detalhe: "Suspenso por decisão do colegiado" },
    { cod: "SE", desc: "NOMEACAO TORNADA SEM EFEITO", detalhe: "Nomeação tornada sem efeito" },
    { cod: "SF", desc: "SEM FINANCEIRO", detalhe: "Sem financeiro" },
    { cod: "SJ", desc: "SUSPENSO P/ ORDEM JUDICIAL", detalhe: "Suspenso por ordem judicial" },
    { cod: "SR", desc: "SEM RECADASTRAMENTO", detalhe: "Sem recadastramento" },
    { cod: "SS", desc: "SUSTADO PELO SISOB", detalhe: "Sustado peo SISOB" },
    { cod: "SV", desc: "SUSTADO RECEBIMENTO VERBA RESIDUAL", detalhe: "Sustado do recebimento de verba residual" },
    { cod: "T0", desc: "A DISPOSICAO", detalhe: "A disposição" },
    { cod: "T1", desc: "DISPOSICAO CESSADA", detalhe: "Disposição cessada" },
    { cod: "T2", desc: "DISPOSICIONADO C/VENCIMENTO ORIGEM", detalhe: "Disposicionado com vencimento para origem" },
    { cod: "T3", desc: "SUSPENSAO CONTRATO", detalhe: "Suspensão de contrato" },
    { cod: "TM", desc: "TERMINO DE MANDATO", detalhe: "Término de mandato" },
    { cod: "TR", desc: "TERMINO DE RESIDENCIA MEDICA", detalhe: "Término de residencia médica" },
    { cod: "U3", desc: "APOSENTADORIA POR INVALIDEZ", detalhe: "Aaposentadoria por invelidez" },
    { cod: "V1", desc: "LICENÇA PARA CASAMENTO", detalhe: "Licença para casamento" },
    { cod: "V2", desc: "AFAST.MOT.FAL.CONJ.COMP.PAIS FILHOS", detalhe: "Afastamento por falecimento de conjuge, companheiro, pais ou filhos" },
    { cod: "V3", desc: "AFAST.EM FACE VIOLEN.DOM.E FAMILIAR", detalhe: "Afastamento em face de violencia domestica e familiar" },
    { cod: "V4", desc: "AFAST.PROG.PROT.A VITIMAS E TESTEM.", detalhe: "Afastamento programa de proteção a vitima e testemunha" },
    { cod: "VE", desc: "REM/COMIS/PERC DEVIDAS CONTR/TRAB", detalhe: "REM/COMIS/PERC DEVIDAS CONTR/TRAB" },
    { cod: "W0", desc: "AFAST.TEMP.EXERC/MANDATO SINDICAL", detalhe: "Afastamento temporário para execicio de mandato sindical" },
    { cod: "W1", desc: "NAO INFORMADO", detalhe: "Não informado" }
];