// Este é o seu banco de dados de situações. 
// Para adicionar novos, basta seguir o padrão.
const dbVinculos = [
    { id: "A", titulo: "ESTATUTARIO", regime: "RPPS", descricao: "Regime Próprio de Previdência Social", detalhe: "Estatutário" },
    { id: "B", titulo: "C.L.T.", regime: "RGPS", descricao: "Regime Geral de Previdência Social", detalhe: "Celetistas" },
    { id: "C", titulo: "REGIME ESPECIAL", regime: "RGPS", descricao: "Regime Geral de Previdência Social", detalhe: "Regime especial" },
    { id: "D", titulo: "CARGO COMISSION.S/VINCULO", regime: "RGPS", descricao: "Regime Geral de Previdência Social", detalhe: "Cargo comissionado sem vínculo" },
    { id: "E", titulo: "RDA-REGIME DE DIREITO ADM", regime: "RGPS", descricao: "Regime Geral de Previdência Social", detalhe: "Regime de direito administrativo" },
    { id: "F", titulo: "SERVICO TEMPORARIO", regime: "RGPS", descricao: "Regime Geral de Previdência Social", detalhe: "Temporários" },
    { id: "G", titulo: "DISP. OUTROS ESFERAS", regime: "RGPS", descricao: "Regime Geral de Previdência Social", detalhe: "À disposição de outras esferas" },
    { id: "H", titulo: "CONSELHO", regime: "RGPS", descricao: "Regime Geral de Previdência Social", detalhe: "Membro de conselho" },
    { id: "I", titulo: "CONSELHO TUTELAR", regime: "RGPS", descricao: "Regime Geral de Previdência Social", detalhe: "Membro conselho tutelar" },
    { id: "J", titulo: "COMISSAO", regime: "RGPS", descricao: "Regime Geral de Previdência Social", detalhe: "Membro de comissão" },
    { id: "K", titulo: "ESTABILIZADO-ESB", regime: "RGPS", descricao: "Regime Geral de Previdência Social", detalhe: "Estabilizado" },
    { id: "L", titulo: "PENSIONISTA POR LEI", regime: "RGPS", descricao: "Regime Geral de Previdência Social", detalhe: "Pensionista hanseniano" },
    { id: "M", titulo: "PENSAO POR LEI", regime: "RGPS", descricao: "Regime Geral de Previdência Social", detalhe: "Pensionista especial por concessão do Estado" },
    { id: "N", titulo: "PENSAO POR DECRETO", regime: "RGPS", descricao: "Regime Geral de Previdência Social", detalhe: "Pensionista especial beneficiário do Policial Militar" },
    { id: "O", titulo: "PENSAO POR ORDEM JUDICIAL", regime: "RGPS", descricao: "Regime Geral de Previdência Social", detalhe: "Pensionista por ordem judicial" },
    { id: "P", titulo: "GRUPO DE TRABALHO", regime: "RGPS", descricao: "Regime Geral de Previdência Social", detalhe: "Membro de grupo de trabalho" },
    { id: "Q", titulo: "BOLSISTA", regime: "RGPS", descricao: "Regime Geral de Previdência Social", detalhe: "Bolsista" },
    { id: "R", titulo: "RESIDENTE", regime: "RGPS", descricao: "Regime Geral de Previdência Social", detalhe: "Médico residente" },
    { id: "S", titulo: "ESTAGIARIO", regime: "RGPS", descricao: "Regime Geral de Previdência Social", detalhe: "Estagiário" },
    { id: "T", titulo: "PROGRAMAS", regime: "RGPS", descricao: "Regime Geral de Previdência Social", detalhe: "Programas" },
    { id: "U", titulo: "PENSAO POR MORTE", regime: "RGPS", descricao: "Regime Geral de Previdência Social", detalhe: "Pensionista por morte" },
    { id: "V", titulo: "VEREADORES", regime: "RGPS", descricao: "Regime Geral de Previdência Social", detalhe: "Vereador" },
    { id: "X", titulo: "TERCEIRIZADO", regime: "RGPS", descricao: "Regime Geral de Previdência Social", detalhe: "Terceirizado" },
    { id: "W", titulo: "HERDEIROS", regime: "RGPS", descricao: "Regime Geral de Previdência Social", detalhe: "Herdeiro" },
    { id: "Y", titulo: "RA_RESERVA ATIVA", regime: "RPPS", descricao: "Regime Próprio de Previdência Social", detalhe: "Militar da reserva ativo" },
    { id: "Z", titulo: "ESPECIAL", regime: "RGPS", descricao: "Regime Geral de Previdência Social", detalhe: "Especial" },
    { id: "1", titulo: "EFETIVO EM CARGO ELETIVO", regime: "RGPS", descricao: "Regime Geral de Previdência Social", detalhe: "Efetivo em cargo eletivo" },
    { id: "2", titulo: "CELETISTA APRENDIZ", regime: "RGPS", descricao: "Regime Geral de Previdência Social", detalhe: "Celetista aprendiz" },
    { id: "3", titulo: "BENEF.NAO PREVIDENCIARIO", regime: "RGPS", descricao: "Regime Geral de Previdência Social", detalhe: "Beneficiário não previdenciário" },
    { id: "4", titulo: "AUTONOMOS", regime: "RGPS", descricao: "Regime Geral de Previdência Social", detalhe: "Autônomo" }
];